### ISSUE TITLE
Create generic modal system

### ISSUE THREAD

**Issue by Sciman101** [IncPlusPlus/beacon-frontend#34]
Modals should be able to display

- Title
- Description
- Arbitrary number of buttons (Ok, yes, no, cancel, etc)
- Arbitrary number of text fields with names and placeholders

The goal is to use this wherever a popup is needed

**Comment by IncPlusPlus** [comment]
Be sure not to waste time reinventing the wheel. I highly recommend using a React component library to handle this. The MUI library has a really nice [modal component](https://mui.com/material-ui/react-modal/). I recommend a google search "modal react component" and seeing what you get.
